
services:
  mysql:
    build: 
      context: ./deploy/mysql
      dockerfile: dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  php1:
    build:
      context: ./TP-Final-3IW-ESGI-main
      dockerfile: dockerfile
    environment:
      SERVEUR_NAME: "Serveur 1"
    container_name: php1
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  php2:
    build:
      context: ./TP-Final-3IW-ESGI-main
      dockerfile: dockerfile
    environment:
      SERVEUR_NAME: "Serveur 2"
    container_name: php2
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./TP-Final-3IW-ESGI-main:/var/www/html
      - ./nginx1:/etc/nginx/conf.d
    depends_on:
      - php1
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Host(`nginx1.localhost`)"
      - "traefik.http.routers.nginx1.entrypoints=web"

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./TP-Final-3IW-ESGI-main:/var/www/html
      - ./nginx2:/etc/nginx/conf.d
    depends_on:
      - php2
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`nginx2.localhost`)"
      - "traefik.http.routers.nginx2.entrypoints=web"

  minio:
    build: 
      context: ./deploy/minio
      dockerfile: dockerfile
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app-network
    volumes:
      - miniodata:/data
    ports:
      - 9000:9000
      - 9001:9001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.localhost`)"
      - "traefik.http.routers.minio.entrypoints=web"

  traefik:
    build: 
      context: ./deploy/traefik
      dockerfile: dockerfile
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.my-dashboard.entrypoints=web"
      - "traefik.http.routers.my-dashboard.service=api@internal"
  
  adminer:
    build: 
      context: ./deploy/adminer
      dockerfile: dockerfile
    container_name: adminer
    restart: always
    ports:
      - "8088:8080"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  miniodata: